services:
    backend:
        image: 'backend-dev'
        build:
            context: .
            dockerfile: ./Dockerfile.dev
            args:
                APP: backend
                BACKEND_PORT: ${BACKEND_PORT}
        volumes:
            - './apps/backend/src:/app/apps/backend/src'
            - '/app/node_modules'
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        environment:
            - BACKEND_PORT=${BACKEND_PORT}
        restart: on-failure

    frontend:
        image: 'frontend-dev'
        build:
            context: .
            dockerfile: ./Dockerfile.dev
            args:
                APP: frontend
                BACKEND_PORT: ${BACKEND_PORT}
                VITE_PORT: ${VITE_PORT}
        volumes:
            - './apps/frontend/src:/app/apps/frontend/src'
            - '/app/node_modules'
        ports:
            - ${VITE_PORT}:${VITE_PORT}
        environment:
            - BACKEND_HOST=backend
            - BACKEND_PORT=${BACKEND_PORT}
            - VITE_PORT=${VITE_PORT}
        depends_on:
            - backend
        restart: on-failure
