services:
  backend:
    image: "backend-prod"
    build:
      context: "./backend"
      dockerfile: "Dockerfile.prod"
    ports:
      - 5000:5000
  frontend:
    image: "frontend-prod"
    build: 
      context: './frontend'
      dockerfile: "Dockerfile.prod"
    ports:
      - 80:80
    env_file:
      - "./frontend/.env"