services:
    backend:
        image: 'backend-prod'
        build:
            context: .
            dockerfile: ./Dockerfile.prod
            target: backend-runner
            args:
                APP: backend
                BACKEND_PORT: ${BACKEND_PORT}
        expose:
            - ${BACKEND_PORT}
        environment:
            - BACKEND_PORT=${BACKEND_PORT}
        restart: unless-stopped

    frontend:
        image: 'frontend-prod'
        build:
            context: .
            dockerfile: ./Dockerfile.prod
            target: frontend-runner
            args:
                APP: frontend
                BACKEND_PORT: ${BACKEND_PORT}
        ports:
            - 80:80
        environment:
            - BACKEND_PORT=${BACKEND_PORT}
            - BACKEND_HOST=backend
        depends_on:
            - backend
        restart: unless-stopped
