services:
    backend:
        image: 'backend-prod'
        build:
            context: .
            dockerfile: ./Dockerfile.prod
            target: backend-runner
            args:
                APP: backend
        ports:
            - 5005:5005
        env_file:
            - './.env.back'
        restart: unless-stopped

    frontend:
        image: 'frontend-prod'
        build:
            context: .
            dockerfile: ./Dockerfile.prod
            target: frontend-runner
            args:
                APP: frontend
        ports:
            - 80:80
        depends_on:
            - backend
        restart: unless-stopped
