services:
    backend:
        image: 'backend-dev'
        build:
            context: .
            dockerfile: ./Dockerfile.dev
            args:
                APP: backend
                WS_PORT: ${WS_PORT}
        volumes:
            - './apps/backend/src:/app/apps/backend/src'
            - '/app/node_modules'
        ports:
            - ${WS_PORT}:${WS_PORT}
        environment:
            - WS_PORT=${WS_PORT}
        restart: on-failure

    frontend:
        image: 'frontend-dev'
        build:
            context: .
            dockerfile: ./Dockerfile.dev
            args:
                APP: frontend
                WS_PORT: ${WS_PORT}
        volumes:
            - './apps/frontend/src:/app/apps/frontend/src'
            - '/app/node_modules'
        ports:
            - ${VITE_PORT}:${VITE_PORT}
        environment:
            - WS_PORT=${WS_PORT}
            - VITE_PORT=${VITE_PORT}
        depends_on:
            - backend
        restart: on-failure
