services:
  backend:
    image: "backend-dev"
    build: "./apps/backend"
    volumes:
      - "./apps/backend/:/app"
      - "/app/node_modules"
    ports:
      - 5005:5005
    env_file:
      - "./.env.back"
    restart: on-failure
    command: ["yarn", "dev"]
  frontend:
    image: "frontend-dev"
    build: ./apps/frontend
    volumes:
      - "./apps/frontend/src:/app/src"
    ports:
      - 5173:5173
    env_file:
      - "./.env.front"
    depends_on:
      - backend
    restart: on-failure
    command: ["yarn", "dev"]