services:
  backend:
    image: "backend-prod"
    build:
      context: "./apps/backend"
      dockerfile: "Dockerfile.prod"
    ports:
      - 5005:5005
    env_file:
      - "./.env.back"
    restart: on-failure
    command: ["npm", "run", "start"]
  frontend:
    image: "frontend-prod"
    build: 
      context: './apps/frontend'
      dockerfile: "Dockerfile.prod"
    ports:
      - 80:80
    env_file:
      - "./.env.front"
    depends_on:
      - backend
    restart: on-failure
    command: ["nginx", "-g", "daemon off;"]