FROM node:20.18.0 AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    else echo "Lockfile not found." && exit 1; \
    fi

COPY . .

RUN yarn build


FROM node:20-alpine

COPY --from=builder /app .

CMD ["npm", "run", "serve"]